/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TelemetryPointInfo { 
    satelliteId: string;
    timestamp: string;
    altitude: number;
    velocity: number;
    status: string;
}

